name: CI for TODO microservices

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eureka-backend:
    name: Build & Push Eureka Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/EurekaServer/eureka

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Eureka image
        uses: docker/build-push-action@v6
        with:
          context: services/EurekaServer/eureka
          push: true
          tags: |
            zamocnikrobert499/eureka-server:latest
            zamocnikrobert499/eureka-server:${{ github.sha }}

  frontend:
    name: Build & Push Angular Frontend
    runs-on: ubuntu-latest
    needs: eureka-backend
    defaults:
      run:
        working-directory: web/angular-app/todo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push frontend image
        uses: docker/build-push-action@v6
        with:
          context: web/angular-app/todo
          push: true
          tags: |
            zamocnikrobert499/todo_frontend:latest
            zamocnikrobert499/todo_frontend:${{ github.sha }}
